# Generated by Django 4.1.6 on 2023-02-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_department_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmpoyeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
