# Generated by Django 4.1.6 on 2023-02-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmpoyeeId',
            new_name='EmployeeId',
        ),
    ]
